stages:
- tests
- tag
- build
- deploy
- release

variables:
    FACTORY_PRODUCT_NAME: wfsOutputExtension
    FACTORY_PACKAGE_NAME: qgis_wfsoutput
    FACTORY_PACKAGE_TYPE: plugin
    FACTORY_MANIFEST: ".lizcloud/factory.manifest"
    GITLAB_SLUG: "lizmap/qgis-wfsoutputextension"

flake8:
  stage: tests
  script:
    - flake8
  tags:
    - factory

test:3.10:
  stage: tests
  script:
    - sed -i "s/^version=.*$/version=${CI_COMMIT_REF_NAME}/g" wfsOutputExtension/metadata.txt
    - make -C tests FLAVOR=3.10
  tags:
    - factory

build:
  stage: build
  script:
    - sed -i "s/^version=.*$/version=${CI_COMMIT_REF_NAME}/g" wfsOutputExtension/metadata.txt
    - make -C .lizcloud -f factory.mk package
  environment:
    name: snap
  artifacts:
    paths:
      - ".lizcloud/factory.manifest"
  tags:
    - infrav3

deploy_snap:
  stage: deploy
  script:
    - sed -i "s/^version=.*$/version=${CI_COMMIT_REF_NAME}/g" wfsOutputExtension/metadata.txt
    - $FACTORY_SCRIPTS/deploy-package $FACTORY_PACKAGE_NAME
  environment:
    name: snap
  tags:
    - infrav3

release_prod:
  stage: release
  script:
    - sed -i "s/^version=.*$/version=${CI_COMMIT_REF_NAME}/g" wfsOutputExtension/metadata.txt
    - $FACTORY_SCRIPTS/release-package $FACTORY_PACKAGE_NAME
  environment:
    name: production
  when: manual
  only:
    - tags
  tags:
    - infrav3

build_2:
  stage: build
  script:
    - sed -i "s/^version=.*$/version=${CI_COMMIT_REF_NAME}/g" wfsOutputExtension/metadata.txt
    - make -C .lizcloud -f fabric.mk package
  environment:
    name: snap
  tags:
    - fabric

deploy_snap_2:
  stage: deploy
  script:
    - sed -i "s/^version=.*$/version=${CI_COMMIT_REF_NAME}/g" wfsOutputExtension/metadata.txt
    - sudo -u fabric fab snap deploy:qgis3_wfsoutput,force=true
  environment:
    name: snap
  tags:
    - fabric

release_prod_2:
  stage: release
  script:
    - sed -i "s/^version=.*$/version=${CI_COMMIT_REF_NAME}/g" wfsOutputExtension/metadata.txt
    - sudo -u fabric fab prod release:qgis3_wfsoutput
  environment:
    name: production
  when: manual
  only:
    - tags
  tags:
    - fabric

tickets:
  stage: release
  only:
    - tags
  image:
    name: registry.snap.lizlan:5000/infra/ci-tools:latest
  script:
    - create_ticket.py
  tags:
    - factory-plain
