stages:
  - build
  - deploy
  - release

build:
  stage: build
  script:
    - make -C .lizcloud -f fabric.mk package
  environment:
    name: snap
  tags:
    - fabric

deploy_snap:
  stage: deploy
  script:
    - sudo -u fabric fab snap deploy:qgis_wfsoutput,force=true
  environment:
    name: snap
  tags:
    - fabric

release_prod:
  stage: release
  script:
    - sudo -u fabric fab prod release:qgis_wfsoutput
  environment:
    name: production
  when: manual
  only:
    - tags
  tags:
    - fabric
