stages:
- build
- deploy
- release

variables:
    FACTORY_PRODUCT_NAME: wfsOutputExtension
    FACTORY_PACKAGE_NAME: qgis_wfsoutput
    FACTORY_PACKAGE_TYPE: plugin
    FACTORY_MANIFEST: ".lizcloud/factory.manifest"

build:
  stage: build
  script:
    - make -C .lizcloud -f factory.mk package
  environment:
    name: snap
  artifacts:
    paths:
      - ".lizcloud/factory.manifest"
  tags:
    - infrav3

deploy_snap:
  stage: deploy
  script:
    - $FACTORY_SCRIPTS/deploy-package $FACTORY_PACKAGE_NAME
  environment:
    name: snap
  tags:
    - infrav3

release_prod:
  stage: release
  script:
    - $FACTORY_SCRIPTS/release_package $FACTORY_PACKAGE_NAME
  environment:
    name: production
  when: manual
  only:
    - tags
  tags:
    - infrav3

