stages:
- tests
- build
- qgis-plugin
- qgis-repository-edit
- qgis-repository-push
- deploy
- release

variables:
    FACTORY_PRODUCT_NAME: wfsOutputExtension
    FACTORY_PACKAGE_TYPE: plugin
    GITLAB_SLUG: "lizmap/qgis-wfsoutputextension"

flake8:
  image: ${REGISTRY_URL}/factory-ci-runner:python
  stage: tests
  script:
    - flake8
  tags:
    - factory-plain

test:
  stage: tests
  parallel:
    matrix:
      - QGIS_VERSION: [
        "3.22",
        "3.28",
        "3.34",
        "3.40",
        "nightly-release",
      ]
  script:
    - make -C tests FLAVOR=${QGIS_VERSION}
  tags:
    - factory-dind

version:
  stage: tests
  image:
    name: $REGISTRY_URI/infra/ci-tools:latest
  script:
    - version-helper
  tags:
    - factory-plain
  artifacts:
    reports:
      dotenv: build.env

package-zip:
  dependencies:
    - version
  stage: build
  image: $REGISTRY_URI/qgis-plugin-ci:latest
  script:
    - >
      qgis-plugin-ci
      package ${VERSION}
      --plugin-repo-url https://packages.3liz.org/pub/${FACTORY_PRODUCT_NAME}-qgis-plugin/${STATUS}/
  tags:
    - factory-plain
  artifacts:
    untracked: true
    expose_as: 'QGIS package'
    paths:
      - ${FACTORY_PRODUCT_NAME}.${VERSION}.zip
      - plugins.xml

push-zip-fetch-repo:
  image: ${REGISTRY_URL}/factory-ci-runner:fabric-ci
  dependencies:
    - version
    - package-zip
  stage: qgis-plugin
  script:
    # Upload into the plugin directory
    - upload_to_packages_server ${FACTORY_PRODUCT_NAME}.${VERSION}.zip pub/${FACTORY_PRODUCT_NAME}-qgis-plugin/${STATUS}/
    - upload_to_packages_server plugins.xml pub/${FACTORY_PRODUCT_NAME}-qgis-plugin/${STATUS}/

    # Fetch XML files
    - mkdir tmp_repository
    - pull_folder_from_packages_server pub/server-plugins-repository/${STATUS}/ tmp_repository

    # This CI job is running as "fabric" user, the next job is "factory"
    - chmod 777 -R tmp_repository/
  tags:
    - fabric
  artifacts:
    paths:
      - tmp_repository/*.xml

edit-repository:
  stage: qgis-repository-edit
  dependencies:
    - package-zip
    - push-zip-fetch-repo
  before_script:
    - PATH=$PATH:~/.local/bin
    - pip3 install --user qgis-plugin-repo
  script:
    - qgis-plugin-repo merge plugins.xml tmp_repository/*.xml
  tags:
    - factory-dind
  artifacts:
    untracked: true
    paths:
      - tmp_repository/*.xml

push-repository:
  image: ${REGISTRY_URL}/factory-ci-runner:fabric-ci
  stage: qgis-repository-push
  dependencies:
    - version
    - edit-repository
  script:
    - upload_folder_to_packages_server tmp_repository/ pub/server-plugins-repository/${STATUS}/
  tags:
    - fabric


#
# Infrav2 packaging
#

deploy_snap_v2:
  image: ${REGISTRY_URL}/factory-ci-runner:fabric-ci
  stage: deploy
  dependencies:
    - push-repository
  script:
    - update-snap-qgis-plugins
  environment:
    name: snap
  tags:
    - fabric

tickets:
  stage: release
  only:
    - tags
  image:
    name: $REGISTRY_URI/infra/ci-tools:latest
  script:
    - create_ticket.py
  tags:
    - factory-plain
