stages:
- tests
- build
- deploy
- release
- edit-repository
- push-repository

variables:
    FACTORY_PRODUCT_NAME: wfsOutputExtension
    FACTORY_PACKAGE_NAME: qgis_wfsoutput
    FACTORY_PACKAGE_TYPE: plugin
    FACTORY_MANIFEST: ".lizcloud/factory.manifest"
    GITLAB_SLUG: "lizmap/qgis-wfsoutputextension"

flake8:
  stage: tests
  script:
    - flake8
  tags:
    - factory

test:
  stage: tests
  parallel:
    matrix:
      - QGIS_VERSION: [
        "3.16",
        "3.22",
        "nightly-release",
      ]
  script:
    - make -C tests FLAVOR=${QGIS_VERSION}
  tags:
    - factory

# Deprecated
check_tag:
  stage: tests
  only:
    - tags
  tags:
    - fabric
  script:
    - .lizcloud/check_tag.sh ${CI_COMMIT_REF_NAME}

version:
  stage: tests
  image:
    name: registry.snap.lizlan:5000/infra/ci-tools:latest
  script:
    - version-helper
  tags:
    - factory-plain
  artifacts:
    reports:
      dotenv: build.env

build:
  stage: build
  script:
    - make -C .lizcloud -f factory.mk package
  environment:
    name: snap
  artifacts:
    paths:
      - ".lizcloud/factory.manifest"
  tags:
    - infrav3

package-zip:
  dependencies:
    - version
  stage: build
  image: registry.snap.lizlan:5000/qgis-plugin-ci:latest
  script:
    - >
      qgis-plugin-ci
      package ${VERSION}
      --plugin-repo-url https://packages.3liz.org/pub/${FACTORY_PRODUCT_NAME}-qgis-plugin/${STATUS}/
  tags:
    - infrav3-plain
  artifacts:
    untracked: true
    expose_as: 'QGIS package'
    paths:
      - ${FACTORY_PRODUCT_NAME}.${VERSION}.zip
      - plugins.xml

push-zip-fetch-repo:
  dependencies:
    - version
    - package-zip
  stage: deploy
  script:
    # Upload into the plugin directory
    - upload_to_packages_server ${FACTORY_PRODUCT_NAME}.${VERSION}.zip pub/${FACTORY_PRODUCT_NAME}-qgis-plugin/${STATUS}/
    - upload_to_packages_server plugins.xml pub/${FACTORY_PRODUCT_NAME}-qgis-plugin/${STATUS}/

    # Fetch XML files
    - mkdir tmp_repository
    - pull_folder_from_packages_server pub/server-plugins-repository/${STATUS}/ tmp_repository

    # This CI job is running as "fabric" user, the next job is "factory"
    - chmod 777 -R tmp_repository/
  tags:
    - fabric
  artifacts:
    paths:
      - tmp_repository/*.xml

deploy_snap:
  stage: deploy
  script:
    - $FACTORY_SCRIPTS/deploy-package $FACTORY_PACKAGE_NAME
  environment:
    name: snap
  tags:
    - infrav3

release_prod:
  stage: release
  script:
    - $FACTORY_SCRIPTS/release-package $FACTORY_PACKAGE_NAME
  environment:
    name: production
  when: manual
  only:
    - tags
  tags:
    - infrav3

build_2:
  stage: build
  script:
    - make -C .lizcloud -f fabric.mk package
  environment:
    name: snap
  tags:
    - fabric

deploy_snap_2:
  stage: deploy
  script:
    - sudo -u fabric fab snap deploy:qgis3_wfsoutput,force=true
  environment:
    name: snap
  tags:
    - fabric

release_prod_2:
  stage: release
  script:
    - sudo -u fabric fab prod release:qgis3_wfsoutput
  environment:
    name: production
  when: manual
  only:
    - tags
  tags:
    - fabric

tickets:
  stage: release
  only:
    - tags
  image:
    name: registry.snap.lizlan:5000/infra/ci-tools:latest
  script:
    - create_ticket.py
  tags:
    - factory-plain

edit-repository:
  stage: edit-repository
  dependencies:
    - package-zip
    - push-zip-fetch-repo
  before_script:
    - PATH=$PATH:~/.local/bin
    - pip3 install --user qgis-plugin-repo
  script:
    - qgis-plugin-repo merge plugins.xml tmp_repository/*.xml
  tags:
    - factory
  artifacts:
    untracked: true
    paths:
      - tmp_repository/*.xml

push-repository:
  stage: push-repository
  dependencies:
    - version
    - edit-repository
  script:
    - upload_folder_to_packages_server tmp_repository/ pub/server-plugins-repository/${STATUS}/
  tags:
    - fabric
