os: linux
dist: bionic
language: python
python: 3.7

services:
  - docker

branches:
  only:
    - master
    - "/^v.*$/"
jobs:
  include:
    - stage: Deploy
      if: tag IS present
      condition: "$TRAVIS_TAG =~ ^v[0-9]+\\.[0-9]+\\.[0-9]+"
      name: Create release, publish on plugins.qgis.org
      install:
        - pip3 install qgis-plugin-ci==1.8.4
      before_deploy:
        - export RELEASE_TITLE=${TRAVIS_TAG:1}
      script:
        - qgis-plugin-ci -v
      deploy:
        - provider: releases
          edge: true
          file: "."
          name: "${RELEASE_TITLE}"
          api_key: "${GH_TOKEN}"
          on:
            tags: true

        - provider: script
          script: >-
            qgis-plugin-ci
            release ${TRAVIS_TAG}
            --github-token ${GH_TOKEN}
            --osgeo-username ${OSGEO_USERNAME}
            --osgeo-password ${OSGEO_PASSWORD}
          on:
            tags: true
